module.exports = {
  REQUEST_FAILURE: 'Failed to',
  DATABASE_CONNECTED: 'Connection has been established successfully.',
  AUTH_MISSING: 'Authorization header is missing',
  ACCESS_REQUIRED: 'Valid access required',
  TOKEN_EXPIRED: 'Token is expired',
  TOKEN_INVALID: 'Token is invalid',
  REGISTERED_SUCCESS: 'registered successfully',
  USER_NOT_FOUND: `User with this email doesn't exist.`,
  ALREADY_REGISTERED: 'already registered',
  FAILED_TO: 'Failed to',
  LOGIN_SUCCESS: 'has been login successfully.',
  DOES_NOT_MATCH: 'does not match.',
  GET_SUCCESS: 'get successfully.',
  TOKEN_MISSING: 'Token is missing',
  NOT_FOUND: 'data not found.',
  ALREADY_EXIST: `already exist.`,
  ALREADY_UPDATE: 'already update.',
  UPDATE_SUCCESS: 'updated successfully.',
};
